galaxy_info:
  author: yourname
  description: Production ClickHouse Role
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: EL
      versions: [8, 9]
    - name: Debian
      versions: [10, 11, 12]

dependencies: []
